main: uk.co.harieo.quackbedwars.ProtectTheEgg
version: 1.0.0
name: ProtectTheEgg
author: Harieo
api-version: '1.15'
depend:
    - MinigamesCore

commands:
    map:
        description: 'Allows you to format the map for this gamemode'
        permission: 'quacktopia.minigames.maps'
        aliases:
            - maps

permissions:
    quacktopia.minigames.join:
        description: 'Allows joining mid-game'
        default: op
    quacktopia.minigames.maps:
        description: 'Allows using /maps command'
        default: op